AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: 'Lambda wrapper for numpy'

Resources:
##################################################################
#
#  Lambda function wrapping numpy
#
##################################################################
  NumpyFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'NumpyWrapper'
      Description: 'Wrapping numpy'
      Handler: 'handler.lambda_handler'
      CodeUri: './code'
      Runtime: 'python2.7'
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          LOG_LEVEL: INFO
